--!strict
return {
	LOBBY_NAME     = "Lobby_Football",
	MAP_NAME       = "Map_FastFood",
	LOBBY_PAD_NAME = "GoToGame",

	LOBBY_PLACE_ID     = 0,
	MATCH_PLACE_ID     = 0,
	MATCH_SIZE         = 4,
	QUEUE_POLL_RATE    = 3,
	MATCH_WAIT_TIMEOUT = 15,
	MEMORY_STORE_NAME  = "MatchQueue",
	DATA_STORE_NAME    = "PlayerStats",

	-- Flyover configuration
	FLYOVER_VELOCITY   = 150,
	FLYOVER_LOOP_DELAY = 20,
}
